[[redirects]]
  from = "/join"
  to = "/join.html"
  status = 200

[[redirects]]
  from = "/refund-policy"
  to = "/refund-policy.html"
  status = 200

[[redirects]]
  from = "/vault"
  to = "/vault.html"
  status = 200

[build]
  publish = "."
